# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

 Create an array of 10 fives

In [7]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

 Create an array of the integers from 10 to 50

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

 Create a 3x3 identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [21]:
np.random.rand(1)

array([0.1887363])

 Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
np.random.randn(5,5)

array([[ 0.01458931, -0.12128743,  0.23563307,  0.8800634 ,  1.01650919],
       [ 0.46619018, -0.20988879, -0.19413805,  0.42672764, -1.79100522],
       [ 0.06806869, -0.94920622, -0.78733207,  1.40886007,  0.13371897],
       [ 1.10387516,  0.03882737,  1.45413342,  2.44102155,  0.20397868],
       [-1.57927953,  1.39441035,  0.87592002, -0.40239648, -0.54385313]])

#### Create the following matrix:

In [29]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [33]:
np.random.rand(1,20)

array([[0.65821518, 0.66651294, 0.57148165, 0.14659886, 0.4693142 ,
        0.36739289, 0.53200523, 0.48983317, 0.63274072, 0.63854642,
        0.31966833, 0.81046591, 0.26533278, 0.96207382, 0.23306627,
        0.27441083, 0.86357653, 0.82425048, 0.75726847, 0.15899232]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [40]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [47]:
x = np.arange(12,24)
x.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [50]:
np.arange(20,21)

20


array([20])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [52]:
z = np.arange(2,13,5)
z.reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [53]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [54]:
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [60]:
mat = np.arange(1,26).reshape(5,5)

print(mat)

np.sum(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


325

#### Get the standard deviation of the values in mat

In [61]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [64]:
mat.sum(0)

array([55, 60, 65, 70, 75])

# Great Job!